import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppRoot from './AppRoot';
import { PropsWithChildren, useState } from 'react';
import { initDB } from './components/db/indexedDB';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang='pl'>
      <body className={inter.className}>
        <AppRoot>{props.children}</AppRoot>
      </body>
    </html>
  );
}
