import '@/src/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AppRoot from './AppRoot';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang='pl'>
      <body className={inter.className}>
        <AppRoot>{props.children}</AppRoot>
        <ToastContainer
          position='bottom-left'
          hideProgressBar
          closeOnClick
          pauseOnHover
          closeButton={false}
        />
      </body>
    </html>
  );
}
